export function useDevtools() {
  const LYRICS = [
    '喔愛 什麼是愛',
    '你看我的眼神怎麼這麼可愛',
    '若是講你的心親像大海',
    '我也會甘願 為了你暈船',
    '喔喔喔愛 什麼是愛',
    '你看我的眼神甘嘸一絲絲愛',
    '真想欲在這個花花世界',
    '帶你去一個 溫暖的所在',
    "Now I just want hold you tight, oh baby don't cry.",
    'I miss you in this rainy night.',
    "I'll show you the best in my mind.",
    "Let's dance in the night.",
    'I will sing a song for you, the love in my eyes.',
    "（I'll write a poem for you, the love in my eyes.）",
    '喔喔喔愛 有你的將來',
    '我對你的感情我講不出來',
    '在這個風風雨雨的世界',
    '你敢會嫌棄 我騎摩托車',
    '喔喔喔愛 有我的未來',
    '我對你的感情我要講出來',
    '在這個風風雨雨的世界',
    '我永遠在這 等你瞭解',
    '喔喔喔愛',
    '喔愛 什麼是愛',
    '你看我的眼神有一絲悲哀',
    '真想欲在這個混亂世界',
    '做你的心中 安身的所在',
    "Now I just want hold you tight, oh baby don't cry.",
    'I miss you in this rainy night.',
    "I'll show you the best in my mind.",
    "Let's dance in the night.",
    "（I'll write a poem for you, the love in my eyes.）",
    '喔喔喔愛 有你的將來',
    '我對你的感情我講不出來',
    '在這個風風雨雨的世界',
    '你敢會嫌棄 我騎摩托車',
    '喔喔喔愛 有我的未來',
    '我對你的感情我要講出來',
    '在這個吵吵鬧鬧的時代',
    '請你站在這 在這聽我說',
    '我喜歡你',
    '喔愛 什麼是愛',
    '我對你的感情甘可以叫作愛',
    '若是有一天你想要瞭解',
    '我永遠在這 我予你時間',
    '喔喔喔愛',
  ]

  function start() {
    console.log(LYRICS.join('\n'))
  }

  return { start }
}
